# vim:ft=kitty

## name:     Catppuccin Kitty Frappé (Pink Edition)
## author:   Customized from Catppuccin Org
## license:  MIT
## blurb:    Pink-forward pastel theme for the high-spirited!

foreground           #c6d0f5
background           #303446
title_fg             #a5adce
title_bg             #292c3c
margin_bg            #292c3c
margin_fg            #a5adce
filler_bg            #292c3c
removed_bg           #7a4b6a
highlight_removed_bg #a05a7a
removed_margin_bg    #8a5268
added_bg             #5a5a66
highlight_added_bg   #6a6a7a
added_margin_bg      #7a5a6a
hunk_margin_bg       #292c3c
hunk_bg              #292c3c
search_bg            #7a6668
search_fg            #c6d0f5
select_bg            #6a4e6a
select_fg            #c6d0f5
